site_name: typedload
site_dir: html
theme: readthedocs
use_directory_urls: false
nav:
    - Home: README.md
    #- Origin story: origin_story.md
    - Changelog: CHANGELOG.md
    - Comparisons: comparisons.md
    - Using typedload:
        - Examples: examples.md
        - Supported types: supported_types.md
        - Errors: errors.md
    #- Tutorial:
    - Contriutors:
        - Contributing: CONTRIBUTING.md
        - Code of conduct: CODE_OF_CONDUCT.md
    - Links:
        - Git: https://github.com/ltworf/typedload/
        - Downloads: https://github.com/ltworf/typedload/releases
        - Bug reports: https://github.com/ltworf/typedload/issues
        - External resources:
            - Debian: https://packages.debian.org/search?keywords=python3-typedload
            - Pypi: https://pypi.org/project/typedload/
            - Pypi stats: https://pypistats.org/packages/typedload
            - Snyk: https://snyk.io/advisor/python/typedload
            - Python Pkg Wiki: https://package.wiki/typedload
