site_name: typedload
theme: readthedocs
nav:
    - Home: README.md
    - Supported types: supported_types.md
    - Examples: examples.md
    - Comparisons: comparisons.md
    - Origin story: origin_story.md
    - Downloads: https://github.com/ltworf/typedload/releases
